### ISSUE TITLE
Hassio Version

### ISSUE THREAD

**Issue by hwikene** [klaasnicolaas/Student-homeassistant-config#1]
Hi! How do you get "hassio version" to show? All i get is NaN and i use the same code as you have

Mine:
<img width="180" alt="Skjermbilde 2019-08-20 kl  22 31 25" src="https://user-images.githubusercontent.com/17985923/63382106-4dd9a580-c39a-11e9-90fa-3bba9ef1b697.png">

```
              - type: vertical-stack
                cards:
                  - type: custom:bar-card
                    title_position: inside
                    entity: sensor.current_version
                    title: Hassio Versjon
                    align: center
                    max: 90
                    padding: 5px
                    card_style:
                      border-radius: 5px
```
